copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkAccelerationStructureBuildTypeKHR.cs VkAccelerationStructureBuildTypeKHR.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkAccelerationStructureCompatibilityKHR.cs VkAccelerationStructureCompatibilityKHR.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkAccelerationStructureCreateFlagBitsKHR.cs VkAccelerationStructureCreateFlagBitsKHR.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkAccelerationStructureMemoryRequirementsTypeNV.cs VkAccelerationStructureMemoryRequirementsTypeNV.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkAccelerationStructureMotionInstanceTypeNV.cs VkAccelerationStructureMotionInstanceTypeNV.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkAccelerationStructureTypeKHR.cs VkAccelerationStructureTypeKHR.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkAccessFlagBits.cs VkAccessFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkAcquireProfilingLockFlagBitsKHR.cs VkAcquireProfilingLockFlagBitsKHR.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkAttachmentDescriptionFlagBits.cs VkAttachmentDescriptionFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkAttachmentLoadOp.cs VkAttachmentLoadOp.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkAttachmentStoreOp.cs VkAttachmentStoreOp.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkBlendFactor.cs VkBlendFactor.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkBlendOp.cs VkBlendOp.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkBlendOverlapEXT.cs VkBlendOverlapEXT.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkBorderColor.cs VkBorderColor.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkBufferCreateFlagBits.cs VkBufferCreateFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkBufferUsageFlagBits.cs VkBufferUsageFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkBuildAccelerationStructureFlagBitsKHR.cs VkBuildAccelerationStructureFlagBitsKHR.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkBuildAccelerationStructureModeKHR.cs VkBuildAccelerationStructureModeKHR.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkChainType.cs VkChainType.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkChromaLocation.cs VkChromaLocation.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkCoarseSampleOrderTypeNV.cs VkCoarseSampleOrderTypeNV.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkColorComponentFlagBits.cs VkColorComponentFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkColorSpaceKHR.cs VkColorSpaceKHR.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkCommandBufferLevel.cs VkCommandBufferLevel.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkCommandBufferUsageFlagBits.cs VkCommandBufferUsageFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkCommandPoolCreateFlagBits.cs VkCommandPoolCreateFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkCommandPoolResetFlagBits.cs VkCommandPoolResetFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkCompareOp.cs VkCompareOp.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkComponentSwizzle.cs VkComponentSwizzle.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkComponentTypeNV.cs VkComponentTypeNV.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkCompositeAlphaFlagBitsKHR.cs VkCompositeAlphaFlagBitsKHR.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkConditionalRenderingFlagBitsEXT.cs VkConditionalRenderingFlagBitsEXT.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkConservativeRasterizationModeEXT.cs VkConservativeRasterizationModeEXT.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkCopyAccelerationStructureModeKHR.cs VkCopyAccelerationStructureModeKHR.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkCoverageModulationModeNV.cs VkCoverageModulationModeNV.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkCoverageReductionModeNV.cs VkCoverageReductionModeNV.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkCullModeFlagBits.cs VkCullModeFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkDebugReportFlagBitsEXT.cs VkDebugReportFlagBitsEXT.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkDebugReportObjectTypeEXT.cs VkDebugReportObjectTypeEXT.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkDebugUtilsMessageSeverityFlagBitsEXT.cs VkDebugUtilsMessageSeverityFlagBitsEXT.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkDebugUtilsMessageTypeFlagBitsEXT.cs VkDebugUtilsMessageTypeFlagBitsEXT.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkDependencyFlagBits.cs VkDependencyFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkDescriptorBindingFlagBits.cs VkDescriptorBindingFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkDescriptorPoolCreateFlagBits.cs VkDescriptorPoolCreateFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkDescriptorSetLayoutCreateFlagBits.cs VkDescriptorSetLayoutCreateFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkDescriptorType.cs VkDescriptorType.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkDescriptorUpdateTemplateType.cs VkDescriptorUpdateTemplateType.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkDeviceDiagnosticsConfigFlagBitsNV.cs VkDeviceDiagnosticsConfigFlagBitsNV.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkDeviceEventTypeEXT.cs VkDeviceEventTypeEXT.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkDeviceGroupPresentModeFlagBitsKHR.cs VkDeviceGroupPresentModeFlagBitsKHR.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkDeviceMemoryReportEventTypeEXT.cs VkDeviceMemoryReportEventTypeEXT.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkDeviceQueueCreateFlagBits.cs VkDeviceQueueCreateFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkDiscardRectangleModeEXT.cs VkDiscardRectangleModeEXT.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkDisplayEventTypeEXT.cs VkDisplayEventTypeEXT.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkDisplayPlaneAlphaFlagBitsKHR.cs VkDisplayPlaneAlphaFlagBitsKHR.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkDisplayPowerStateEXT.cs VkDisplayPowerStateEXT.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkDriverId.cs VkDriverId.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkDynamicState.cs VkDynamicState.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkEventCreateFlagBits.cs VkEventCreateFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkExternalFenceFeatureFlagBits.cs VkExternalFenceFeatureFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkExternalFenceHandleTypeFlagBits.cs VkExternalFenceHandleTypeFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkExternalMemoryFeatureFlagBits.cs VkExternalMemoryFeatureFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkExternalMemoryFeatureFlagBitsNV.cs VkExternalMemoryFeatureFlagBitsNV.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkExternalMemoryHandleTypeFlagBits.cs VkExternalMemoryHandleTypeFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkExternalMemoryHandleTypeFlagBitsNV.cs VkExternalMemoryHandleTypeFlagBitsNV.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkExternalSemaphoreFeatureFlagBits.cs VkExternalSemaphoreFeatureFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkExternalSemaphoreHandleTypeFlagBits.cs VkExternalSemaphoreHandleTypeFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkFenceCreateFlagBits.cs VkFenceCreateFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkFenceImportFlagBits.cs VkFenceImportFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkFilter.cs VkFilter.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkFormat.cs VkFormat.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkFormatFeatureFlagBits.cs VkFormatFeatureFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkFragmentShadingRateCombinerOpKHR.cs VkFragmentShadingRateCombinerOpKHR.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkFragmentShadingRateNV.cs VkFragmentShadingRateNV.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkFragmentShadingRateTypeNV.cs VkFragmentShadingRateTypeNV.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkFramebufferCreateFlagBits.cs VkFramebufferCreateFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkFrontFace.cs VkFrontFace.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkGeometryFlagBitsKHR.cs VkGeometryFlagBitsKHR.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkGeometryInstanceFlagBitsKHR.cs VkGeometryInstanceFlagBitsKHR.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkGeometryTypeKHR.cs VkGeometryTypeKHR.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkIcdWsiPlatform.cs VkIcdWsiPlatform.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkImageAspectFlagBits.cs VkImageAspectFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkImageCreateFlagBits.cs VkImageCreateFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkImageLayout.cs VkImageLayout.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkImageTiling.cs VkImageTiling.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkImageType.cs VkImageType.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkImageUsageFlagBits.cs VkImageUsageFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkImageViewCreateFlagBits.cs VkImageViewCreateFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkImageViewType.cs VkImageViewType.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkIndexType.cs VkIndexType.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkIndirectCommandsLayoutUsageFlagBitsNV.cs VkIndirectCommandsLayoutUsageFlagBitsNV.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkIndirectCommandsTokenTypeNV.cs VkIndirectCommandsTokenTypeNV.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkIndirectStateFlagBitsNV.cs VkIndirectStateFlagBitsNV.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkInternalAllocationType.cs VkInternalAllocationType.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkLayerFunction.cs VkLayerFunction.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkLineRasterizationModeEXT.cs VkLineRasterizationModeEXT.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkLoaderFeastureFlagBits.cs VkLoaderFeastureFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkLogicOp.cs VkLogicOp.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkMemoryAllocateFlagBits.cs VkMemoryAllocateFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkMemoryHeapFlagBits.cs VkMemoryHeapFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkMemoryOverallocationBehaviorAMD.cs VkMemoryOverallocationBehaviorAMD.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkMemoryPropertyFlagBits.cs VkMemoryPropertyFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkNegotiateLayerStructType.cs VkNegotiateLayerStructType.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkObjectType.cs VkObjectType.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkPeerMemoryFeatureFlagBits.cs VkPeerMemoryFeatureFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkPerformanceConfigurationTypeINTEL.cs VkPerformanceConfigurationTypeINTEL.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkPerformanceCounterDescriptionFlagBitsKHR.cs VkPerformanceCounterDescriptionFlagBitsKHR.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkPerformanceCounterScopeKHR.cs VkPerformanceCounterScopeKHR.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkPerformanceCounterStorageKHR.cs VkPerformanceCounterStorageKHR.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkPerformanceCounterUnitKHR.cs VkPerformanceCounterUnitKHR.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkPerformanceOverrideTypeINTEL.cs VkPerformanceOverrideTypeINTEL.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkPerformanceParameterTypeINTEL.cs VkPerformanceParameterTypeINTEL.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkPerformanceValueTypeINTEL.cs VkPerformanceValueTypeINTEL.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkPhysicalDeviceType.cs VkPhysicalDeviceType.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkPipelineBindPoint.cs VkPipelineBindPoint.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkPipelineCacheCreateFlagBits.cs VkPipelineCacheCreateFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkPipelineCacheHeaderVersion.cs VkPipelineCacheHeaderVersion.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkPipelineCompilerControlFlagBitsAMD.cs VkPipelineCompilerControlFlagBitsAMD.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkPipelineCreateFlagBits.cs VkPipelineCreateFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkPipelineCreationFeedbackFlagBitsEXT.cs VkPipelineCreationFeedbackFlagBitsEXT.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkPipelineExecutableStatisticFormatKHR.cs VkPipelineExecutableStatisticFormatKHR.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkPipelineShaderStageCreateFlagBits.cs VkPipelineShaderStageCreateFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkPipelineStageFlagBits.cs VkPipelineStageFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkPointClippingBehavior.cs VkPointClippingBehavior.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkPolygonMode.cs VkPolygonMode.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkPresentModeKHR.cs VkPresentModeKHR.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkPrimitiveTopology.cs VkPrimitiveTopology.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkPrivateDataSlotCreateFlagBitsEXT.cs VkPrivateDataSlotCreateFlagBitsEXT.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkProvokingVertexModeEXT.cs VkProvokingVertexModeEXT.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkQueryControlFlagBits.cs VkQueryControlFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkQueryPipelineStatisticFlagBits.cs VkQueryPipelineStatisticFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkQueryPoolSamplingModeINTEL.cs VkQueryPoolSamplingModeINTEL.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkQueryResultFlagBits.cs VkQueryResultFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkQueryType.cs VkQueryType.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkQueueFlagBits.cs VkQueueFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkQueueGlobalPriorityEXT.cs VkQueueGlobalPriorityEXT.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkRasterizationOrderAMD.cs VkRasterizationOrderAMD.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkRayTracingShaderGroupTypeKHR.cs VkRayTracingShaderGroupTypeKHR.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkRenderPassCreateFlagBits.cs VkRenderPassCreateFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkResolveModeFlagBits.cs VkResolveModeFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkSampleCountFlagBits.cs VkSampleCountFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkSamplerAddressMode.cs VkSamplerAddressMode.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkSamplerCreateFlagBits.cs VkSamplerCreateFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkSamplerMipmapMode.cs VkSamplerMipmapMode.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkSamplerReductionMode.cs VkSamplerReductionMode.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkSamplerYcbcrModelConversion.cs VkSamplerYcbcrModelConversion.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkSamplerYcbcrRange.cs VkSamplerYcbcrRange.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkScopeNV.cs VkScopeNV.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkSemaphoreImportFlagBits.cs VkSemaphoreImportFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkSemaphoreType.cs VkSemaphoreType.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkSemaphoreWaitFlagBits.cs VkSemaphoreWaitFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkShaderCorePropertiesFlagBitsAMD.cs VkShaderCorePropertiesFlagBitsAMD.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkShaderFloatControlsIndependence.cs VkShaderFloatControlsIndependence.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkShaderGroupShaderKHR.cs VkShaderGroupShaderKHR.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkShaderInfoTypeAMD.cs VkShaderInfoTypeAMD.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkShaderStageFlagBits.cs VkShaderStageFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkShadingRatePaletteEntryNV.cs VkShadingRatePaletteEntryNV.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkSharingMode.cs VkSharingMode.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkSparseImageFormatFlagBits.cs VkSparseImageFormatFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkSparseMemoryBindFlagBits.cs VkSparseMemoryBindFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkStencilFaceFlagBits.cs VkStencilFaceFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkStencilOp.cs VkStencilOp.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkStructureType.cs VkStructureType.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkSubgroupFeatureFlagBits.cs VkSubgroupFeatureFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkSubmitFlagBitsKHR.cs VkSubmitFlagBitsKHR.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkSubpassContents.cs VkSubpassContents.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkSubpassDescriptionFlagBits.cs VkSubpassDescriptionFlagBits.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkSurfaceCounterFlagBitsEXT.cs VkSurfaceCounterFlagBitsEXT.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkSurfaceTransformFlagBitsKHR.cs VkSurfaceTransformFlagBitsKHR.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkSwapchainCreateFlagBitsKHR.cs VkSwapchainCreateFlagBitsKHR.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkSystemAllocationScope.cs VkSystemAllocationScope.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkTessellationDomainOrigin.cs VkTessellationDomainOrigin.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkTimeDomainEXT.cs VkTimeDomainEXT.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkToolPurposeFlagBitsEXT.cs VkToolPurposeFlagBitsEXT.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkValidationCacheHeaderVersionEXT.cs VkValidationCacheHeaderVersionEXT.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkValidationCheckEXT.cs VkValidationCheckEXT.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkValidationFeatureDisableEXT.cs VkValidationFeatureDisableEXT.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkValidationFeatureEnableEXT.cs VkValidationFeatureEnableEXT.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkVendorId.cs VkVendorId.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkVertexInputRate.cs VkVertexInputRate.cs
copy D:\AssemblyCache\Vulkan\wrappers\Vulkan\VkViewportCoordinateSwizzleNV.cs VkViewportCoordinateSwizzleNV.cs