namespace Vulkan
{
    public enum VkDebugReportObjectTypeEXT : uint
    {
        Unknown                  = 0,
        Instance                 = 1,
        PhysicalDevice           = 2,
        Device                   = 3,
        Queue                    = 4,
        Semaphore                = 5,
        CommandBuffer            = 6,
        Fence                    = 7,
        DeviceMemory             = 8,
        Buffer                   = 9,
        Image                    = 10,
        Event                    = 11,
        QueryPool                = 12,
        BufferView               = 13,
        ImageView                = 14,
        ShaderModule             = 15,
        PipelineCache            = 16,
        PipelineLayout           = 17,
        RenderPass               = 18,
        Pipeline                 = 19,
        DescriptorSetLayout      = 20,
        Sampler                  = 21,
        DescriptorPool           = 22,
        DescriptorSet            = 23,
        Framebuffer              = 24,
        CommandPool              = 25,
        Surface                  = 26,
        Swapchain                = 27,
        DebugReportCallback      = 28,
        Display                  = 29,
        DisplayMode              = 30,
        ValidationCache          = 33,
        SamplerYcbcrConversion   = 1000156000,
        DescriptorUpdateemplate  = 1000085000,
        CuModulex                = 1000029000,
        CuFunctionx              = 1000029001,
        AccelerationStructureKhr = 1000150000,
        AccelerationStructureNv  = 1000165000,
        BufferCollectionFuchsia  = 1000366000,
        MaxEnumFlag              = 0x7FFFFFFF
    }
}
